# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  akshayapatravms-app:
    image: ardahal/akshayapatravms:latest
    environment:
      - _JAVA_OPTIONS=-Xmx1024m -Xms512m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://akshayapatravms-postgresql:5432/AkshayaPatraVMS
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://akshayapatravms-postgresql:5432/AkshayaPatraVMS
      - EMAIL_SENDING_ADDRESS="${EMAIL_SENDING_ADDRESS}"
      - EMAIL_SENDING_PASS="${EMAIL_SENDING_PASS}"
      - JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET="$JHIPSTER_SECURITY_AUTHENTICATION_JWT_BASE64_SECRET"
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  akshayapatravms-postgresql:
    image: postgres:14.1
    # volumes:
    #   - ~/volumes/jhipster/AkshayaPatraVMS/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=AkshayaPatraVMS
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
